# Generated by Django 4.0.5 on 2022-06-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('thumbnail', models.URLField(verbose_name='썸네일')),
                ('explain', models.TextField(verbose_name='설명')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('show_start_date', models.DateTimeField(verbose_name='노출시작일')),
                ('show_stop_date', models.DateTimeField(verbose_name='노출 종료일')),
                ('alive', models.BooleanField(default=0, verbose_name='활성화 여부')),
            ],
        ),
    ]
