# Generated by Django 4.0.5 on 2022-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_evnet_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='alive',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='event',
            name='show_start_date',
            field=models.DateField(verbose_name='노출시작일'),
        ),
        migrations.AlterField(
            model_name='event',
            name='show_stop_date',
            field=models.DateField(verbose_name='노출 종료일'),
        ),
    ]
