# Generated by Django 4.0.5 on 2022-06-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_alive_event_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(upload_to='static/img/product/thumbnail', verbose_name='썸네일'),
        ),
    ]
