# Generated by Django 4.0.5 on 2022-06-22 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_alter_event_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='상품이름')),
                ('thumbnail', models.ImageField(upload_to='static/img/product', verbose_name='썸네일')),
                ('explain', models.TextField(verbose_name='상품설명')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('show_start_date', models.DateField(verbose_name='노출시작일')),
                ('show_stop_date', models.DateField(verbose_name='노출 종료일')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('is_active', models.BooleanField(default=0, verbose_name='활성화 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
