# Generated by Django 4.0.5 on 2022-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('네스프레소', (('오리지널', 'Original'), ('버츄오', 'Vertuo'))), ('네스카페 돌체구스토', 'NESCAFE Dolce Gusto'), ('일리', 'illy'), ('라바짜', (('EP', 'EP'), ('아모도미오', 'Amodomio')))], max_length=100, verbose_name='커피머신 브랜드')),
            ],
        ),
    ]
