# Generated by Django 4.0.5 on 2022-06-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='장르')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='가수이름')),
                ('gender', models.BooleanField(verbose_name='성별(True가 여)')),
                ('solo', models.BooleanField(verbose_name='솔로 혹은 그룹')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='노래제목')),
                ('lyrics', models.TextField(verbose_name='가사')),
                ('release_date', models.DateTimeField(verbose_name='발매일')),
                ('remake_singer', models.ManyToManyField(related_name='remake_singer', to='homework.singer', verbose_name='리메이크 가수')),
                ('singer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homework.singer', verbose_name='원곡자')),
            ],
        ),
    ]
