# Generated by Django 4.0.5 on 2022-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(default=0, verbose_name='성별'),
        ),
    ]
